# src/Shop/ShopBundle/Resources/config/routing.yml
ShopBundle_homepage:
    path:     /
    defaults: { _controller: "ShopBundle:Page:index" }
    requirements:
         methods:  GET

ShopBundle_about:
    path:   /about
    defaults: { _controller: "ShopBundle:Page:about" }
    requirements:
         methods:  GET

ShopBundle_contact:
    path:   /contact
    defaults: { _controller: "ShopBundle:Page:contact" }
    requirements:
         methods:  GET | POST

ShopBundle_table:
    path:   /table
    defaults: { _controller: "ShopBundle:Table:table" }
    requirements:
         methods:  GET

ShopBundle_insert:
    path:   /insert
    defaults: { _controller: "ShopBundle:Table:insert" }
    requirements:
         methods:  GET